window.RENTHUB_DATA = {
  categories: [
    { value: "Accommodation", label: "Accommodation", icon: "&#127968;" },
    { value: "Vehicles", label: "Vehicles", icon: "&#128663;" },
    { value: "Cameras", label: "Cameras", icon: "&#128247;" },
    { value: "Gaming", label: "Gaming", icon: "&#127918;" },
    { value: "Audio", label: "Audio", icon: "&#128266;" },
    { value: "Tools", label: "Tools", icon: "&#128736;" },
    { value: "Event Equipment", label: "Event Equipment", icon: "&#127881;" },
    { value: "Electronics", label: "Electronics", icon: "&#128187;" },
    { value: "Boats & Marine", label: "Boats & Marine", icon: "&#9973;" },
    { value: "Sports & Fitness", label: "Sports & Fitness", icon: "&#9917;" },
    { value: "Furniture", label: "Furniture", icon: "&#128715;" },
    { value: "Fashion", label: "Fashion", icon: "&#128087;" }
  ],
  islands: [
    { atoll: "MLE", name: "Male'" },
    { atoll: "MLE", name: "Hulhumale'" },
    { atoll: "MLE", name: "Villimale'" },
    { atoll: "HA", name: "Baarah" },
    { atoll: "HA", name: "Dhiddhoo" },
    { atoll: "HA", name: "Filladhoo" },
    { atoll: "HA", name: "Hoarafushi" },
    { atoll: "HA", name: "Ihavandhoo" },
    { atoll: "HA", name: "Kelaa" },
    { atoll: "HA", name: "Maarandhoo" },
    { atoll: "HA", name: "Mulhadhoo" },
    { atoll: "HA", name: "Muraidhoo" },
    { atoll: "HA", name: "Thakandhoo" },
    { atoll: "HA", name: "Thuraakunu" },
    { atoll: "HA", name: "Uligamu" },
    { atoll: "HA", name: "Utheemu" },
    { atoll: "HA", name: "Vashafaru" },
    { atoll: "HDh", name: "Finey" },
    { atoll: "HDh", name: "Hanimaadhoo" },
    { atoll: "HDh", name: "Hirimaradhoo" },
    { atoll: "HDh", name: "Kulhudhuffushi" },
    { atoll: "HDh", name: "Kumundhoo" },
    { atoll: "HDh", name: "Kurinbi" },
    { atoll: "HDh", name: "Makunudhoo" },
    { atoll: "HDh", name: "Naivaadhoo" },
    { atoll: "HDh", name: "Nellaidhoo" },
    { atoll: "HDh", name: "Neykurendhoo" },
    { atoll: "HDh", name: "Nolhivaramu" },
    { atoll: "HDh", name: "Nolhivaranfaru" },
    { atoll: "HDh", name: "Vaikaradhoo" },
    { atoll: "Sh", name: "Bileffahi" },
    { atoll: "Sh", name: "Feevah" },
    { atoll: "Sh", name: "Feydhoo" },
    { atoll: "Sh", name: "Foakaidhoo" },
    { atoll: "Sh", name: "Funadhoo" },
    { atoll: "Sh", name: "Goidhoo" },
    { atoll: "Sh", name: "Kanditheemu" },
    { atoll: "Sh", name: "Komandoo" },
    { atoll: "Sh", name: "Lhaimagu" },
    { atoll: "Sh", name: "Maaungoodhoo" },
    { atoll: "Sh", name: "Maroshi" },
    { atoll: "Sh", name: "Milandhoo" },
    { atoll: "Sh", name: "Narudhoo" },
    { atoll: "Sh", name: "Noomaraa" },
    { atoll: "N", name: "Foddhoo" },
    { atoll: "N", name: "Henbadhoo" },
    { atoll: "N", name: "Holhudhoo" },
    { atoll: "N", name: "Kendhikulhudhoo" },
    { atoll: "N", name: "Kudafari" },
    { atoll: "N", name: "Landhoo" },
    { atoll: "N", name: "Lhohi" },
    { atoll: "N", name: "Maafaru" },
    { atoll: "N", name: "Maalhendhoo" },
    { atoll: "N", name: "Magoodhoo" },
    { atoll: "N", name: "Manadhoo" },
    { atoll: "N", name: "Miladhoo" },
    { atoll: "N", name: "Velidhoo" },
    { atoll: "R", name: "Alifushi" },
    { atoll: "R", name: "Angolhitheemu" },
    { atoll: "R", name: "Dhuvaafaru" },
    { atoll: "R", name: "Fainu" },
    { atoll: "R", name: "Hulhudhuffaaru" },
    { atoll: "R", name: "Inguraidhoo" },
    { atoll: "R", name: "Innamaadhoo" },
    { atoll: "R", name: "Kinolhas" },
    { atoll: "R", name: "Maakurathu" },
    { atoll: "R", name: "Maduvvaree" },
    { atoll: "R", name: "Meedhoo" },
    { atoll: "R", name: "Rasgetheemu" },
    { atoll: "R", name: "Rasmaadhoo" },
    { atoll: "R", name: "Ungoofaaru" },
    { atoll: "R", name: "Vaadhoo" },
    { atoll: "B", name: "Dharavandhoo" },
    { atoll: "B", name: "Dhonfanu" },
    { atoll: "B", name: "Eydhafushi" },
    { atoll: "B", name: "Fehendhoo" },
    { atoll: "B", name: "Fulhadhoo" },
    { atoll: "B", name: "Goidhoo" },
    { atoll: "B", name: "Hithaadhoo" },
    { atoll: "B", name: "Kamadhoo" },
    { atoll: "B", name: "Kendhoo" },
    { atoll: "B", name: "Kihaadhoo" },
    { atoll: "B", name: "Kudarikilu" },
    { atoll: "B", name: "Maalhos" },
    { atoll: "B", name: "Thulhaadhoo" },
    { atoll: "Lh", name: "Hinnavaru" },
    { atoll: "Lh", name: "Kurendhoo" },
    { atoll: "Lh", name: "Maafilaafushi" },
    { atoll: "Lh", name: "Naifaru" },
    { atoll: "Lh", name: "Olhuvelifushi" },
    { atoll: "Lh", name: "Ookolhufinolhu" },
    { atoll: "K", name: "Dhiffushi" },
    { atoll: "K", name: "Gaafaru" },
    { atoll: "K", name: "Gulhi" },
    { atoll: "K", name: "Guraidhoo" },
    { atoll: "K", name: "Himmafushi" },
    { atoll: "K", name: "Hulhumale'" },
    { atoll: "K", name: "Huraa" },
    { atoll: "K", name: "Kaashidhoo" },
    { atoll: "K", name: "Maafushi" },
    { atoll: "K", name: "Male'" },
    { atoll: "K", name: "Thulusdhoo" },
    { atoll: "K", name: "Villimale'" },
    { atoll: "AA", name: "Bodufolhudhoo" },
    { atoll: "AA", name: "Feridhoo" },
    { atoll: "AA", name: "Fesdhoo" },
    { atoll: "AA", name: "Himandhoo" },
    { atoll: "AA", name: "Maalhos" },
    { atoll: "AA", name: "Mathiveri" },
    { atoll: "AA", name: "Rasdhoo" },
    { atoll: "AA", name: "Thoddoo" },
    { atoll: "AA", name: "Ukulhas" },
    { atoll: "ADh", name: "Dhangethi" },
    { atoll: "ADh", name: "Dhiddhoo" },
    { atoll: "ADh", name: "Dhigurah" },
    { atoll: "ADh", name: "Fenfushi" },
    { atoll: "ADh", name: "Hangnaameedhoo" },
    { atoll: "ADh", name: "Kunburudhoo" },
    { atoll: "ADh", name: "Maamigili" },
    { atoll: "ADh", name: "Mahibadhoo" },
    { atoll: "ADh", name: "Mandhoo" },
    { atoll: "ADh", name: "Omadhoo" },
    { atoll: "V", name: "Felidhoo" },
    { atoll: "V", name: "Fulidhoo" },
    { atoll: "V", name: "Keyodhoo" },
    { atoll: "V", name: "Rakeedhoo" },
    { atoll: "V", name: "Thinadhoo" },
    { atoll: "M", name: "Dhiggaru" },
    { atoll: "M", name: "Kolhufushi" },
    { atoll: "M", name: "Maduvvaree" },
    { atoll: "M", name: "Mulah" },
    { atoll: "M", name: "Muli" },
    { atoll: "M", name: "Naalaafushi" },
    { atoll: "M", name: "Raimmandhoo" },
    { atoll: "M", name: "Veyvah" },
    { atoll: "F", name: "Bileddhoo" },
    { atoll: "F", name: "Dharanboodhoo" },
    { atoll: "F", name: "Feeali" },
    { atoll: "F", name: "Magoodhoo" },
    { atoll: "F", name: "Nilandhoo" },
    { atoll: "Dh", name: "Bandidhoo" },
    { atoll: "Dh", name: "Hulhudheli" },
    { atoll: "Dh", name: "Kudahuvadhoo" },
    { atoll: "Dh", name: "Maaenboodhoo" },
    { atoll: "Dh", name: "Meedhoo" },
    { atoll: "Dh", name: "Rinbudhoo" },
    { atoll: "Dh", name: "Vaanee" },
    { atoll: "Th", name: "Burunee" },
    { atoll: "Th", name: "Dhiyamingili" },
    { atoll: "Th", name: "Gaadhiffushi" },
    { atoll: "Th", name: "Guraidhoo" },
    { atoll: "Th", name: "Hirilandhoo" },
    { atoll: "Th", name: "Kandoodhoo" },
    { atoll: "Th", name: "Kinbidhoo" },
    { atoll: "Th", name: "Madifushi" },
    { atoll: "Th", name: "Omadhoo" },
    { atoll: "Th", name: "Thimarafushi" },
    { atoll: "Th", name: "Vandhoo" },
    { atoll: "Th", name: "Veymandoo" },
    { atoll: "Th", name: "Vilufushi" },
    { atoll: "L", name: "Dhanbidhoo" },
    { atoll: "L", name: "Fonadhoo" },
    { atoll: "L", name: "Gan" },
    { atoll: "L", name: "Hithadhoo" },
    { atoll: "L", name: "Isdhoo" },
    { atoll: "L", name: "Kalaidhoo" },
    { atoll: "L", name: "Kunahandhoo" },
    { atoll: "L", name: "Maabaidhoo" },
    { atoll: "L", name: "Maamendhoo" },
    { atoll: "L", name: "Maavah" },
    { atoll: "GA", name: "Dhaandhoo" },
    { atoll: "GA", name: "Dhevvadhoo" },
    { atoll: "GA", name: "Gemanafushi" },
    { atoll: "GA", name: "Kanduhulhudhoo" },
    { atoll: "GA", name: "Kolamaafushi" },
    { atoll: "GA", name: "Kondey" },
    { atoll: "GA", name: "Maamendhoo" },
    { atoll: "GA", name: "Nilandhoo" },
    { atoll: "GA", name: "Villingili" },
    { atoll: "GDh", name: "Fares-Maathodaa" },
    { atoll: "GDh", name: "Fiyoaree" },
    { atoll: "GDh", name: "Gadhdhoo" },
    { atoll: "GDh", name: "Hoandeddhoo" },
    { atoll: "GDh", name: "Madaveli" },
    { atoll: "GDh", name: "Nadellaa" },
    { atoll: "GDh", name: "Rathafandhoo" },
    { atoll: "GDh", name: "Thinadhoo" },
    { atoll: "GDh", name: "Vaadhoo" },
    { atoll: "Gn", name: "Fuvahmulah" },
    { atoll: "S", name: "Feydhoo" },
    { atoll: "S", name: "Hithadhoo" },
    { atoll: "S", name: "Hulhudhoo" },
    { atoll: "S", name: "Maradhoo" },
    { atoll: "S", name: "Maradhoo-Feydhoo" },
    { atoll: "S", name: "Meedhoo" }
  ],
  listings: [
    {
      title: "Sony Alpha Creator Kit",
      category: "Cameras",
      price: "MVR 450/day",
      location: "Male' (K)",
      image: "assets/listing-camera.png",
      description: "Camera body, portrait lens, batteries, tripod, and creator accessories.",
      phone: "9607000000"
    },
    {
      title: "Lagoon View Apartment",
      category: "Accommodation",
      price: "MVR 1,800/day",
      location: "Hulhumale' (K)",
      image: "assets/listing-apartment.png",
      description: "Bright apartment near the beach with verified owner contact.",
      phone: "9607000001"
    },
    {
      title: "Island Ready Compact Car",
      category: "Vehicles",
      price: "MVR 650/day",
      location: "Hithadhoo (S)",
      image: "assets/listing-car.png",
      description: "Comfortable compact car for local errands and family trips.",
      phone: "9607000002"
    },
    {
      title: "DJI Aerial Shoot Kit",
      category: "Electronics",
      price: "MVR 520/day",
      location: "Maafushi (K)",
      image: "assets/listing-drone.png",
      description: "Drone kit with spare batteries for island shoots and events.",
      phone: "9607000003"
    },
    {
      title: "Event Speaker Pair",
      category: "Audio",
      price: "MVR 350/day",
      location: "Male' (K)",
      image: "assets/listing-speaker.png",
      description: "Two powered speakers for birthdays, meetings, and pop-up events.",
      phone: "9607000004"
    },
    {
      title: "4K Meeting Projector",
      category: "Event Equipment",
      price: "MVR 290/day",
      location: "Hulhumale' (K)",
      image: "assets/listing-projector.png",
      description: "Portable projector with HDMI cable and compact carry case.",
      phone: "9607000005"
    },
    {
      title: "PlayStation 5 Bundle",
      category: "Gaming",
      price: "MVR 300/day",
      location: "Thulusdhoo (K)",
      image: "assets/listing-projector.png",
      description: "Console, two controllers, and party games for weekend rental.",
      phone: "9607000006"
    },
    {
      title: "Cordless Tool Set",
      category: "Tools",
      price: "MVR 180/day",
      location: "Kulhudhuffushi (HDh)",
      image: "assets/listing-speaker.png",
      description: "Drill, driver, charger, and essential bits for home projects.",
      phone: "9607000007"
    },
    {
      title: "Speedboat Day Charter",
      category: "Boats & Marine",
      price: "MVR 4,500/day",
      location: "Maafushi (K)",
      image: "assets/listing-car.png",
      description: "Boat rental with captain for nearby transfers and day trips.",
      phone: "9607000008"
    },
    {
      title: "MacBook Pro Workstation",
      category: "Electronics",
      price: "MVR 420/day",
      location: "Villimale' (K)",
      image: "assets/listing-camera.png",
      description: "Laptop rental for editing, presentations, and short-term work.",
      phone: "9607000009"
    }
  ]
};
